version: "3.0"

services:
  api:
    build:
      context: .
    image: inverview-challenges
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
      - auth
    networks:
      - internal
    ports:
      - "3000:3000"

  auth:
    build:
      context: .
    image: inverview-challenges
    env_file: docker-compose.env
    environment:
      SERVICES: auth
    depends_on:
      - nats
      - es
    networks:
      - internal

  es:
    build:
      context: .
    image: inverview-challenges
    env_file: docker-compose.env
    environment:
      SERVICES: es
    depends_on:
      - nats
      - elasticsearch
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200

networks:
  internal:
