version: "3.0"

services:
  api:
    build:
      context: .
    image: inverview-challenges-1
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    networks:
      - internal
    ports:
      - "3000:3000"

  auth:
    build:
      context: .
    image: inverview-challenges-1
    env_file: docker-compose.env
    environment:
      SERVICES: auth
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

networks:
  internal:
