apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: appropriate/curl
            args:
              - /bin/sh
              - -c
              - curl https://localhost/cron-endpoint 
          restartPolicy: OnFailure