apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/mhm0ud/helloworld-python
        env:
        - name: TARGET
          value: "Python Sample v1"
    # The secret data is exposed to Containers in the Pod through a Volume.
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: db-secret 
  
    